# Generated by Django 3.0.5 on 2020-04-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='nutrition_facts',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pizza',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
