# Generated by Django 3.0.5 on 2020-04-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200419_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='nutrition_facts',
            field=models.TextField(default=''),
        ),
    ]
