# Generated by Django 3.0.5 on 2020-04-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200421_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='nutrition_facts',
        ),
        migrations.AddField(
            model_name='pizza',
            name='carbohydrates',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pizza',
            name='energy_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pizza',
            name='fats',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pizza',
            name='proteins',
            field=models.IntegerField(default=1),
        ),
    ]
